version: "3"

services:
  db:
    build:
      context: ./DockerPostgresql
      dockerfile: db.Dockerfile
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: anpi
      POSTGRES_DB: anpi
      POSTGRES_PASSWORD: anpi
    ports:
      - "5432:5432"
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db