-- anpimolduras.aglomerado definition
drop table if exists aglomerado;
CREATE TABLE "aglomerado" (
  "id_aglomerado" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_aglomerado")
);


-- anpimolduras.carton definition
drop table if exists carton;
CREATE TABLE "carton" (
  "id_carton" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_carton")
);


-- anpimolduras.clientes definition
drop table if exists clientes;
CREATE TABLE "clientes" (
  "id_cliente" numeric(12) NOT NULL,
  "nombre" varchar(255) DEFAULT NULL,
  "apellido" varchar(255) DEFAULT NULL,
  "cedula" numeric(12,2) DEFAULT NULL,
  "numero" varchar(255) DEFAULT NULL,
  "direccion" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id_cliente")
);


-- anpimolduras.corte definition
drop table if exists corte;
CREATE TABLE "corte" (
  "id_corte" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_corte")
);


-- anpimolduras.exposures definition
drop table if exists exposures;
CREATE TABLE "exposures" (
  "id" numeric(12) NOT NULL,
  "type" varchar(50) NOT NULL,
  PRIMARY KEY ("id")
);


-- anpimolduras.molduras definition
drop table if exists molduras;
CREATE TABLE "molduras" (
  "id_moldura" numeric(12) NOT NULL,
  "nombre" varchar(255) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_moldura")
);


-- anpimolduras.paspartu definition
drop table if exists paspartu;
CREATE TABLE "paspartu" (
  "id_paspartu" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_paspartu")
);


-- anpimolduras.terminado definition
drop table if exists terminado;
CREATE TABLE "terminado" (
  "id_terminado" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_terminado")
);


-- anpimolduras.usuarios definition
drop table if exists usuarios;
CREATE TABLE "usuarios" (
  "id" numeric(12) NOT NULL,
  "email" varchar(255) NOT NULL,
  "encrypted_password" varchar(255) NOT NULL,
  "first_name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "user_id" varchar(255) NOT NULL,
  "limit_date" date DEFAULT NULL,
  "limit_danger_date" date DEFAULT NULL,
  PRIMARY KEY ("id"),
  unique("user_id"),
  unique("email")
);


-- anpimolduras.vidrio_n definition
drop table if exists vidrio_n;
CREATE TABLE "vidrio_n" (
  "id_vidrio_n" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_vidrio_n")
);


-- anpimolduras.vidrio_sr definition
drop table if exists vidrio_sr;
CREATE TABLE "vidrio_sr" (
  "id_vidrio_sr" numeric(12) NOT NULL,
  "centimetros" numeric(12,2) DEFAULT NULL,
  "precio" numeric(12,2) NOT NULL,
  PRIMARY KEY ("id_vidrio_sr")
);

CREATE SEQUENCE "Sid_molduraS" START 500;

--aglomerado
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(1, 45, 0.33);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(2, 50, 0.36);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(3, 55, 0.44);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(4, 60, 0.53);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(5, 65, 0.61);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(6, 70, 0.7);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(7, 75, 0.79);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(8, 80, 0.92);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(9, 85, 1.05);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(10, 90, 1.21);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(11, 95, 1.26);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(12, 100, 1.42);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(13, 105, 1.57);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(14, 110, 1.73);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(15, 115, 1.87);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(16, 120, 2.04);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(17, 125, 2.22);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(18, 130, 2.39);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(19, 135, 2.61);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(20, 140, 2.77);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(21, 145, 2.98);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(22, 150, 3.21);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(23, 155, 3.41);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(24, 160, 3.63);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(25, 165, 3.87);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(26, 170, 4.1);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(27, 175, 4.36);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(28, 180, 4.59);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(29, 185, 4.84);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(30, 190, 5.14);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(31, 195, 5.4);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(32, 200, 5.69);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(33, 205, 5.97);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(34, 210, 6.27);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(35, 215, 6.54);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(36, 220, 6.86);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(37, 225, 7.5);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(38, 230, 7.84);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(39, 235, 8.16);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(40, 240, 8.46);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(41, 245, 8.79);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(42, 250, 9.11);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(43, 255, 9.45);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(44, 260, 9.76);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(45, 265, 10.09);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(46, 270, 10.41);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(47, 275, 10.75);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(48, 280, 11.39);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(49, 285, 11.71);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(50, 290, 12.04);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(51, 295, 12.36);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(52, 300, 12.69);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(53, 305, 13.01);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(54, 310, 13.34);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(55, 315, 13.66);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(56, 320, 13.99);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(57, 325, 14.31);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(58, 330, 14.64);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(59, 335, 14.96);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(60, 340, 15.29);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(61, 345, 15.61);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(62, 350, 15.94);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(63, 355, 16.26);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(64, 360, 16.59);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(65, 365, 16.91);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(66, 370, 17.24);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(67, 375, 17.56);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(68, 380, 17.89);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(69, 385, 18.21);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(70, 390, 18.55);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(71, 395, 18.86);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(72, 400, 19.19);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(73, 405, 19.51);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(74, 410, 19.84);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(75, 415, 20.16);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(76, 420, 20.49);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(77, 425, 20.81);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(78, 430, 21.14);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(79, 435, 21.46);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(80, 440, 21.81);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(81, 445, 22.11);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(82, 450, 22.44);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(83, 455, 22.76);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(84, 460, 23.09);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(85, 465, 23.69);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(86, 470, 24.19);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(87, 475, 24.71);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(88, 480, 25.23);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(89, 485, 25.75);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(90, 490, 26.27);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(91, 495, 26.82);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(92, 500, 27.35);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(93, 505, 27.9);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(94, 510, 28.44);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(95, 515, 29.0);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(96, 520, 29.56);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(97, 525, 30.12);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(98, 530, 30.69);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(99, 535, 31.28);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(100, 540, 31.86);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(101, 545, 32.45);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(102, 550, 33.03);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(103, 555, 33.63);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(104, 560, 34.24);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(105, 565, 34.85);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(106, 570, 35.46);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(107, 575, 36.08);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(108, 580, 36.7);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(109, 585, 37.34);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(110, 590, 37.97);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(111, 595, 38.62);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(112, 600, 39.27);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(113, 605, 39.4);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(114, 610, 40.57);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(115, 615, 41.22);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(116, 620, 41.9);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(117, 625, 42.56);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(118, 630, 43.25);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(119, 635, 43.93);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(120, 640, 44.62);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(121, 645, 45.32);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(122, 650, 46.01);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(123, 655, 46.72);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(124, 660, 47.42);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(125, 665, 48.14);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(126, 670, 48.87);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(127, 675, 49.6);
INSERT INTO aglomerado ("id_aglomerado", "centimetros", "precio") VALUES(128, 680, 50.39);

--carton
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(1, 45, 0.04);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(2, 50, 0.05);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(3, 55, 0.07);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(4, 60, 0.08);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(5, 65, 0.09);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(6, 70, 0.1);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(7, 75, 0.12);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(8, 80, 0.14);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(9, 85, 0.16);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(10, 90, 0.17);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(11, 95, 0.2);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(12, 100, 0.22);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(13, 105, 0.23);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(14, 110, 0.27);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(15, 115, 0.29);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(16, 120, 0.31);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(17, 125, 0.34);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(18, 130, 0.36);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(19, 135, 0.4);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(20, 140, 0.42);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(21, 145, 0.46);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(22, 150, 0.48);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(23, 155, 0.53);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(24, 160, 0.55);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(25, 165, 0.59);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(26, 170, 0.62);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(27, 175, 0.66);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(28, 180, 0.69);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(29, 185, 0.73);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(30, 190, 0.79);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(31, 195, 0.82);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(32, 200, 0.86);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(33, 205, 0.9);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(34, 210, 0.95);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(35, 215, 0.99);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(36, 220, 0.92);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(37, 225, 1.09);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(38, 230, 1.13);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(39, 235, 1.18);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(40, 240, 1.24);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(41, 245, 1.29);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(42, 250, 1.34);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(43, 255, 1.39);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(44, 260, 1.46);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(45, 265, 1.51);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(46, 270, 1.56);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(47, 275, 1.63);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(48, 280, 1.68);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(49, 285, 1.74);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(50, 290, 1.81);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(51, 295, 1.87);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(52, 300, 1.94);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(53, 305, 1.99);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(54, 310, 2.07);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(55, 315, 2.13);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(56, 320, 2.2);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(57, 325, 2.26);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(58, 330, 2.34);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(59, 335, 2.41);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(60, 340, 2.48);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(61, 345, 2.55);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(62, 350, 2.63);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(63, 355, 2.7);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(64, 360, 2.78);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(65, 365, 2.86);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(66, 370, 2.94);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(67, 375, 3.02);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(68, 380, 3.09);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(69, 385, 3.19);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(70, 390, 3.26);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(71, 395, 3.34);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(72, 400, 3.43);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(73, 405, 3.52);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(74, 410, 3.6);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(75, 415, 3.69);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(76, 420, 3.78);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(77, 425, 3.87);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(78, 430, 3.97);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(79, 435, 4.06);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(80, 440, 4.15);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(81, 445, 4.25);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(82, 450, 4.34);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(83, 455, 4.45);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(84, 460, 4.54);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(85, 465, 4.64);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(86, 470, 4.73);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(87, 475, 4.84);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(88, 480, 4.94);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(89, 485, 5.04);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(90, 490, 5.15);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(91, 495, 5.25);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(92, 500, 5.37);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(93, 505, 5.47);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(94, 510, 5.58);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(95, 515, 5.69);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(96, 520, 5.8);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(97, 525, 5.92);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(98, 530, 6.02);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(99, 535, 6.14);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(100, 540, 6.25);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(101, 545, 6.37);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(102, 550, 6.49);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(103, 555, 6.6);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(104, 560, 6.72);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(105, 565, 6.85);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(106, 570, 6.97);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(107, 575, 7.1);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(108, 580, 7.22);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(109, 585, 7.35);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(110, 590, 7.46);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(111, 595, 7.59);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(112, 600, 7.72);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(113, 605, 7.85);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(114, 610, 7.98);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(115, 615, 8.11);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(116, 620, 8.24);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(117, 625, 8.39);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(118, 630, 8.52);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(119, 635, 8.65);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(120, 640, 8.79);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(121, 645, 8.92);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(122, 650, 9.06);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(123, 655, 9.2);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(124, 660, 9.35);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(125, 665, 9.49);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(126, 670, 9.63);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(127, 675, 9.78);
INSERT INTO carton ("id_carton", "centimetros", "precio") VALUES(128, 680, 9.92);

--corte
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(1, 45, 0.01);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(2, 50, 0.03);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(3, 55, 0.04);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(4, 60, 0.05);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(5, 65, 0.07);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(6, 70, 0.08);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(7, 75, 0.09);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(8, 80, 0.1);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(9, 85, 0.12);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(10, 90, 0.14);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(11, 95, 0.16);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(12, 100, 0.17);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(13, 105, 0.18);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(14, 110, 0.2);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(15, 115, 0.21);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(16, 120, 0.22);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(17, 125, 0.23);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(18, 130, 0.25);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(19, 135, 0.27);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(20, 140, 0.29);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(21, 145, 0.3);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(22, 150, 0.31);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(23, 155, 0.33);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(24, 160, 0.34);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(25, 165, 0.35);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(26, 170, 0.36);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(27, 175, 0.38);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(28, 180, 0.4);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(29, 185, 0.42);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(30, 190, 0.43);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(31, 195, 0.44);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(32, 200, 0.46);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(33, 205, 0.47);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(34, 210, 0.48);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(35, 215, 0.49);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(36, 220, 0.51);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(37, 225, 0.53);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(38, 230, 0.55);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(39, 235, 0.56);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(40, 240, 0.57);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(41, 245, 0.59);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(42, 250, 0.6);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(43, 255, 0.61);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(44, 260, 0.62);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(45, 265, 0.64);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(46, 270, 0.65);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(47, 275, 0.66);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(48, 280, 0.68);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(49, 285, 0.69);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(50, 290, 0.7);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(51, 295, 0.72);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(52, 300, 0.73);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(53, 305, 0.74);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(54, 310, 0.75);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(55, 315, 0.77);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(56, 320, 0.78);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(57, 325, 0.79);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(58, 330, 0.81);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(59, 335, 0.82);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(60, 340, 0.83);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(61, 345, 0.85);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(62, 350, 0.86);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(63, 355, 0.87);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(64, 360, 0.88);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(65, 365, 0.9);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(66, 370, 0.91);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(67, 375, 0.92);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(68, 380, 0.94);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(69, 385, 0.95);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(70, 390, 0.96);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(71, 395, 0.98);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(72, 400, 0.99);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(73, 405, 1.0);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(74, 410, 1.01);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(75, 415, 1.03);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(76, 420, 1.04);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(77, 425, 1.05);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(78, 430, 1.07);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(79, 435, 1.08);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(80, 440, 1.09);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(81, 445, 1.11);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(82, 450, 1.12);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(83, 455, 1.13);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(84, 460, 1.14);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(85, 465, 1.16);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(86, 470, 1.17);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(87, 475, 1.18);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(88, 480, 1.2);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(89, 485, 1.21);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(90, 490, 1.22);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(91, 495, 1.24);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(92, 500, 1.25);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(93, 505, 1.26);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(94, 510, 1.27);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(95, 515, 1.29);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(96, 520, 1.3);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(97, 525, 1.31);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(98, 530, 1.33);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(99, 535, 1.34);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(100, 540, 1.35);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(101, 545, 1.37);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(102, 550, 1.38);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(103, 555, 1.39);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(104, 560, 1.4);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(105, 565, 1.42);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(106, 570, 1.43);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(107, 575, 1.44);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(108, 580, 1.46);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(109, 585, 1.47);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(110, 590, 1.48);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(111, 595, 1.5);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(112, 600, 1.51);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(113, 605, 1.52);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(114, 610, 1.53);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(115, 615, 1.55);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(116, 620, 1.56);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(117, 625, 1.57);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(118, 630, 1.59);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(119, 635, 1.6);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(120, 640, 1.61);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(121, 645, 1.63);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(122, 650, 1.64);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(123, 655, 1.65);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(124, 660, 1.66);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(125, 665, 1.68);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(126, 670, 1.69);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(127, 675, 1.7);
INSERT INTO corte ("id_corte", "centimetros", "precio") VALUES(128, 680, 1.72);

--molduiras
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(1, NULL, 0.0);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(2, 'BASTIDOR', 4.94);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(3, 'REFUERZO', 3.5);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(4, 'A5-018', 4.94);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(5, 'A5-039', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(6, 'A10-01', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(7, 'A10-018', 8.32);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(8, 'A14-01', 6.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(9, 'A14-01E', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(10, 'A15-01', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(11, 'A15-80VM', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(12, 'A25-02', 5.72);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(13, 'A30-01', 2.86);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(14, 'A30-08', 3.38);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(15, 'A35-01', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(16, 'A40-01', 5.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(17, 'A40-08', 5.06);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(18, 'A45-01E', 5.68);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(19, 'A45-01', 6.5);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(20, 'A50-01', 5.46);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(21, 'A50-FC', 5.98);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(22, 'A55-01E', 7.3);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(23, 'A55-018', 6.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(24, 'A60-01', 4.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(25, 'A70-01', 5.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(26, 'A70-018', 6.12);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(27, 'A80-01A', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(28, 'A80-01', 7.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(29, 'A95-01E', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(30, 'A95-018', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(31, 'A5-028', 4.94);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(32, 'A5-FO9', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(33, 'A10-02', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(34, 'A10-028', 8.32);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(35, 'A14-02F', 6.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(36, 'A5-038', 4.94);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(37, 'A5-02FE', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(38, 'A10-01E', 7.68);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(39, 'A5-048', 4.94);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(40, 'A15-02', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(41, ' A15-28VM', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(42, 'A15-03', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(43, 'A15-ES', 5.52);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(44, 'A30-02', 2.86);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(45, 'A30-09', 3.38);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(46, 'A35-02', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(47, 'A40-02', 5.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(48, 'A40-036', 5.06);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(49, 'A30-04', 2.86);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(50, 'A30-ES', 2.86);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(51, 'A35-02F', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(52, 'A40-03', 5.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(53, 'A40-04', 5.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(54, 'A40-ES', 5.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(55, 'A50-02', 5.46);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(56, 'A50-03', 5.46);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(57, 'A50-04', 5.46);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(58, 'A50-00', 5.46);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(59, 'A55-02E', 7.3);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(60, 'A55-028', 6.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(61, 'A60-02', 4.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(62, 'A70-02', 5.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(63, 'A70-038', 6.12);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(64, 'A55-02FE', 7.3);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(65, 'A55-038', 6.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(66, 'A60-03', 4.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(67, 'A70-ES', 5.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(68, 'A55-048', 6.62);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(69, 'A60-ES', 4.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(70, 'A80-02', 7.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(71, 'A80-03', 7.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(72, 'A95-02E', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(73, 'A95-028', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(74, 'A95-02FE ', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(75, 'A95-078', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(76, 'A95-098', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(77, 'A100-018', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(78, 'A105-01', 6.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(79, 'A105-170', 7.66);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(80, 'A110-018', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(81, 'A115-018', 10.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(82, 'A120-01', 10.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(83, 'A130-01', 14.04);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(84, 'A130-FPO', 15.6);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(85, 'A135-01', 9.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(86, 'A135-FC', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(87, 'A140-18', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(88, 'A140-01', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(89, 'A140-14', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(90, 'A140-01VG', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(91, 'A150-01', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(92, 'A150-01A', 7.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(93, 'A150-FC', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(94, 'A155-01E', 14.04);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(95, 'A165-02', 10.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(96, 'A170-02', 10.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(97, 'A175-018', 11.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(98, 'A180-02', 16.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(99, 'A185-028F', 13.64);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(100, 'A190-01', 10.66);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(101, 'A195-01', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(102, 'A200-01', 20.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(103, 'A205-01', 9.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(104, 'A205-02', 9.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(105, 'A205-193', 10.26);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(106, 'A105-02', 6.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(107, 'A105-40VM', 7.66);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(108, 'A110-028', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(109, 'A115-028', 10.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(110, 'A120-02', 10.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(111, 'A130-02', 14.04);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(112, 'A130-57VM', 15.6);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(113, 'A135-02', 9.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(114, 'A135-FPO', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(115, 'A140-28', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(116, 'A140-02', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(117, 'A140-15', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(118, 'A150-02', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(119, 'A150-08', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(120, 'A170-02F', 10.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(121, 'A175-028', 11.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(122, 'A195-02', 7.28);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(123, 'A200-02', 20.54);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(124, 'A105-03', 6.76);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(125, 'A105-37EM', 7.66);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(126, 'A110-18N', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(127, 'A110-01N', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(128, 'A130-28VM', 15.6);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(129, 'A135-36', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(130, 'A140-38', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(131, 'A135-28VM', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(132, 'A150-ES', 7.02);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(133, 'A150-FO9', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(134, 'A150-FCE', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(135, 'A150-FCO', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(136, 'A150-FP', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(137, 'A150-FPO', 7.92);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(138, 'A170-02FE', 10.14);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(139, 'A175-028F', 11.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(140, 'A210-01', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(141, 'A210-FC', 8.58);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(142, 'A215-018E', 22.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(143, 'A220-01', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(144, 'A225-01', 9.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(145, 'A225-46AB', 10.4);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(146, 'A230-02', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(147, 'A230-20EM', 10.26);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(148, 'A235-01', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(149, 'A235-33VM', 10.0);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(150, 'A240-01', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(151, 'A240-43M', 5.84);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(152, 'A245-01', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(153, 'A250-20EM', 15.6);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(154, 'A255-80VM', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(155, 'A260-31M', 11.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(156, 'A265-39P', 13.64);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(157, 'A270-80VM', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(158, 'A275-FPO', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(159, 'A280-43VM', 9.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(160, 'A285-FC', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(161, 'A290-69M', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(162, 'A295-35', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(163, 'A210-02', 8.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(164, 'A210-FPO', 8.58);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(165, 'A220-02', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(166, 'A225-02', 9.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(167, 'A230-42CM', 10.26);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(168, 'A235-02-ES', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(169, 'A240-170VM', 5.84);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(170, 'A245-02', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(171, 'A255-193', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(172, 'A260-55AB', 11.18);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(173, 'A265-39M', 13.64);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(174, 'A270-72EM', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(175, 'A275-39VM', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(176, 'A280-80VM', 9.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(177, 'A285-73EM', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(178, 'A290-38M', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(179, 'A295-45', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(180, 'A210-55CM', 8.58);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(181, 'A220-02F', 5.2);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(182, 'A230-55AV', 10.26);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(183, 'A235-ES', 9.1);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(184, 'A240-39VM', 5.84);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(185, 'A255-12VM', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(186, 'A270-98M', 7.8);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(187, 'A275-35EM', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(188, 'A280-170', 9.88);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(189, 'A290-73M', 8.44);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(190, 'A295-64EM', 8.7);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(191, 'A230-72EM', 10.26);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(192, 'A240-33VM', 5.84);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(193, 'A255-FO9', 10.78);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(194, 'A275-72EM', 15.08);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(195, '501', 10.49);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(196, '1017-80', 22.81);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(197, '1030-44', 21.19);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(198, '1103-S', 27.31);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(199, '1123-04', 26.21);
INSERT INTO molduras ("id_moldura", "nombre", "precio") VALUES(200, '1169-43', 26.08);

--paspartu
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(1, 45, 0.33);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(2, 50, 0.36);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(3, 55, 0.44);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(4, 60, 0.53);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(5, 65, 0.61);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(6, 70, 0.7);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(7, 75, 0.79);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(8, 80, 0.92);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(9, 85, 1.05);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(10, 90, 1.21);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(11, 95, 1.26);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(12, 100, 1.42);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(13, 105, 1.57);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(14, 110, 1.73);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(15, 115, 1.87);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(16, 120, 2.04);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(17, 125, 2.22);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(18, 130, 2.39);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(19, 135, 2.61);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(20, 140, 2.77);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(21, 145, 2.98);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(22, 150, 3.21);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(23, 155, 3.41);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(24, 160, 3.63);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(25, 165, 3.87);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(26, 170, 4.1);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(27, 175, 4.36);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(28, 180, 4.59);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(29, 185, 4.84);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(30, 190, 5.14);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(31, 195, 5.4);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(32, 200, 5.69);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(33, 205, 5.97);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(34, 210, 6.27);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(35, 215, 6.54);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(36, 220, 6.86);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(37, 225, 7.5);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(38, 230, 7.84);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(39, 235, 8.16);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(40, 240, 8.46);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(41, 245, 8.79);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(42, 250, 9.11);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(43, 255, 9.45);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(44, 260, 9.76);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(45, 265, 10.09);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(46, 270, 10.41);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(47, 275, 10.75);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(48, 280, 11.39);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(49, 285, 11.71);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(50, 290, 12.04);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(51, 295, 12.36);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(52, 300, 12.69);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(53, 305, 13.01);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(54, 310, 13.34);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(55, 315, 13.66);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(56, 320, 13.99);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(57, 325, 14.31);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(58, 330, 14.64);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(59, 335, 14.96);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(60, 340, 15.29);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(61, 345, 15.61);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(62, 350, 15.94);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(63, 355, 16.26);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(64, 360, 16.59);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(65, 365, 16.91);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(66, 370, 17.24);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(67, 375, 17.56);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(68, 380, 17.89);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(69, 385, 18.21);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(70, 390, 18.55);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(71, 395, 18.86);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(72, 400, 19.19);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(73, 405, 19.51);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(74, 410, 19.84);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(75, 415, 20.16);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(76, 420, 20.49);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(77, 425, 20.81);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(78, 430, 21.14);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(79, 435, 21.46);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(80, 440, 21.81);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(81, 445, 22.11);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(82, 450, 22.44);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(83, 455, 22.76);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(84, 460, 23.09);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(85, 465, 23.69);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(86, 470, 24.19);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(87, 475, 24.71);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(88, 480, 25.23);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(89, 485, 25.75);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(90, 490, 26.27);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(91, 495, 26.82);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(92, 500, 27.35);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(93, 505, 27.9);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(94, 510, 28.44);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(95, 515, 29.0);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(96, 520, 29.56);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(97, 525, 30.12);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(98, 530, 30.69);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(99, 535, 31.28);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(100, 540, 31.86);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(101, 545, 32.45);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(102, 550, 33.03);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(103, 555, 33.63);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(104, 560, 34.24);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(105, 565, 34.85);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(106, 570, 35.46);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(107, 575, 36.08);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(108, 580, 36.7);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(109, 585, 37.34);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(110, 590, 37.97);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(111, 595, 38.62);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(112, 600, 39.27);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(113, 605, 39.4);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(114, 610, 40.57);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(115, 615, 41.22);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(116, 620, 41.9);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(117, 625, 42.56);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(118, 630, 43.25);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(119, 635, 43.93);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(120, 640, 44.62);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(121, 645, 45.32);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(122, 650, 46.01);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(123, 655, 46.72);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(124, 660, 47.42);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(125, 665, 48.14);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(126, 670, 48.87);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(127, 675, 49.6);
INSERT INTO paspartu ("id_paspartu", "centimetros", "precio") VALUES(128, 680, 50.39);

--terminado
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(1, 45, 0.01);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(2, 50, 0.03);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(3, 55, 0.04);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(4, 60, 0.05);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(5, 65, 0.07);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(6, 70, 0.08);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(7, 75, 0.09);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(8, 80, 0.1);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(9, 85, 0.12);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(10, 90, 0.14);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(11, 95, 0.16);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(12, 100, 0.17);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(13, 105, 0.18);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(14, 110, 0.2);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(15, 115, 0.21);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(16, 120, 0.22);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(17, 125, 0.23);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(18, 130, 0.25);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(19, 135, 0.27);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(20, 140, 0.29);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(21, 145, 0.3);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(22, 150, 0.31);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(23, 155, 0.33);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(24, 160, 0.34);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(25, 165, 0.35);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(26, 170, 0.36);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(27, 175, 0.38);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(28, 180, 0.4);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(29, 185, 0.42);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(30, 190, 0.43);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(31, 195, 0.44);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(32, 200, 0.46);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(33, 205, 0.47);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(34, 210, 0.48);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(35, 215, 0.49);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(36, 220, 0.51);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(37, 225, 0.53);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(38, 230, 0.55);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(39, 235, 0.56);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(40, 240, 0.57);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(41, 245, 0.59);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(42, 250, 0.6);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(43, 255, 0.61);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(44, 260, 0.62);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(45, 265, 0.64);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(46, 270, 0.65);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(47, 275, 0.66);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(48, 280, 0.68);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(49, 285, 0.69);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(50, 290, 0.7);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(51, 295, 0.72);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(52, 300, 0.73);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(53, 305, 0.74);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(54, 310, 0.75);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(55, 315, 0.77);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(56, 320, 0.78);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(57, 325, 0.79);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(58, 330, 0.81);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(59, 335, 0.82);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(60, 340, 0.83);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(61, 345, 0.85);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(62, 350, 0.86);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(63, 355, 0.87);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(64, 360, 0.88);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(65, 365, 0.9);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(66, 370, 0.91);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(67, 375, 0.92);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(68, 380, 0.94);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(69, 385, 0.95);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(70, 390, 0.96);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(71, 395, 0.98);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(72, 400, 0.99);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(73, 405, 1.0);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(74, 410, 1.01);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(75, 415, 1.03);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(76, 420, 1.04);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(77, 425, 1.05);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(78, 430, 1.07);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(79, 435, 1.08);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(80, 440, 1.09);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(81, 445, 1.11);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(82, 450, 1.12);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(83, 455, 1.13);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(84, 460, 1.14);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(85, 465, 1.16);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(86, 470, 1.17);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(87, 475, 1.18);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(88, 480, 1.2);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(89, 485, 1.21);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(90, 490, 1.22);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(91, 495, 1.24);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(92, 500, 1.25);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(93, 505, 1.26);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(94, 510, 1.27);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(95, 515, 1.29);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(96, 520, 1.3);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(97, 525, 1.31);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(98, 530, 1.33);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(99, 535, 1.34);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(100, 540, 1.35);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(101, 545, 1.37);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(102, 550, 1.38);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(103, 555, 1.39);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(104, 560, 1.4);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(105, 565, 1.42);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(106, 570, 1.43);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(107, 575, 1.44);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(108, 580, 1.46);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(109, 585, 1.47);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(110, 590, 1.48);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(111, 595, 1.5);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(112, 600, 1.51);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(113, 605, 1.52);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(114, 610, 1.53);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(115, 615, 1.55);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(116, 620, 1.56);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(117, 625, 1.57);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(118, 630, 1.59);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(119, 635, 1.6);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(120, 640, 1.61);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(121, 645, 1.63);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(122, 650, 1.64);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(123, 655, 1.65);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(124, 660, 1.66);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(125, 665, 1.68);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(126, 670, 1.69);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(127, 675, 1.7);
INSERT INTO terminado ("id_terminado", "centimetros", "precio") VALUES(128, 680, 1.72);

--users
INSERT INTO usuarios ("id", "email", "encrypted_password", "first_name", "last_name", "user_id", "limit_date", "limit_danger_date") VALUES(1, 'test@gmail.com', '$2a$10$y71z/r19xdjkSyDtFnqD3elhwirFSY9KX6rhg8D.9DFP/l8LE1Sou', 'esteban', 'rosero', 'dcb1dc51-a3b8-4b8a-88fe-ee3e56fabea9', '2023-12-31', NULL);
INSERT INTO usuarios ("id", "email", "encrypted_password", "first_name", "last_name", "user_id", "limit_date", "limit_danger_date") VALUES(2, 'gabygallegos@anpimarcos.com', '$2a$10$0s7eIY.DIQ8yI6O8Hwt34uyUbdhZHyb23RYmv8cUwtQ6JnaZi8wWq', 'Gaby', 'Gallegos', 'fec6b14f-6892-40c7-8f47-2b70e2fe4832', '2023-12-31', NULL);
INSERT INTO usuarios ("id", "email", "encrypted_password", "first_name", "last_name", "user_id", "limit_date", "limit_danger_date") VALUES(3, 'ximeVanegas@anpimarcos.com', '$2a$10$5kpJGAd2FzhAbBxuegZRo.2FefFcLwsBB/KzZHO/Tjq/t/R.ZJXfW', 'Xime', 'Vanegas', '370dd8a6-51e0-4db6-a704-46a6f2b75ece', '2023-11-30', NULL);

--vidrio n
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(1, 45, 0.16);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(2, 50, 0.17);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(3, 55, 0.22);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(4, 60, 0.27);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(5, 65, 0.3);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(6, 70, 0.34);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(7, 75, 0.4);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(8, 80, 0.46);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(9, 85, 0.53);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(10, 90, 0.59);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(11, 95, 0.66);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(12, 100, 0.73);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(13, 105, 0.79);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(14, 110, 0.87);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(15, 115, 0.94);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(16, 120, 1.01);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(17, 125, 1.11);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(18, 130, 1.24);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(19, 135, 1.31);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(20, 140, 1.39);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(21, 145, 1.48);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(22, 150, 1.59);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(23, 155, 1.7);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(24, 160, 1.83);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(25, 165, 1.94);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(26, 170, 2.04);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(27, 175, 2.17);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(28, 180, 2.3);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(29, 185, 2.42);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(30, 190, 2.56);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(31, 195, 2.69);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(32, 200, 2.83);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(33, 205, 2.98);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(34, 210, 3.13);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(35, 215, 3.28);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(36, 220, 3.45);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(37, 225, 3.59);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(38, 230, 3.74);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(39, 235, 3.91);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(40, 240, 4.08);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(41, 245, 4.25);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(42, 250, 4.43);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(43, 255, 4.6);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(44, 260, 4.8);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(45, 265, 4.98);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(46, 270, 5.16);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(47, 275, 5.34);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(48, 280, 5.55);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(49, 285, 5.75);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(50, 290, 5.95);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(51, 295, 6.16);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(52, 300, 6.38);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(53, 305, 6.58);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(54, 310, 6.81);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(55, 315, 7.03);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(56, 320, 7.25);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(57, 325, 7.48);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(58, 330, 7.71);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(59, 335, 7.96);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(60, 340, 8.18);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(61, 345, 8.42);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(62, 350, 8.67);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(63, 355, 8.92);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(64, 360, 9.18);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(65, 365, 9.43);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(66, 370, 9.7);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(67, 375, 9.96);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(68, 380, 10.23);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(69, 385, 10.49);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(70, 390, 10.76);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(71, 395, 11.04);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(72, 400, 11.32);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(73, 405, 11.61);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(74, 410, 11.9);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(75, 415, 12.19);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(76, 420, 12.49);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(77, 425, 12.78);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(78, 430, 13.09);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(79, 435, 13.4);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(80, 440, 13.7);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(81, 445, 14.01);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(82, 450, 14.33);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(83, 455, 14.66);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(84, 460, 14.98);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(85, 465, 15.3);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(86, 470, 15.63);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(87, 475, 15.98);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(88, 480, 16.3);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(89, 485, 16.65);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(90, 490, 16.99);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(91, 495, 17.34);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(92, 500, 17.71);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(93, 505, 18.04);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(94, 510, 18.41);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(95, 515, 18.77);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(96, 520, 19.14);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(97, 525, 19.51);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(98, 530, 19.88);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(99, 535, 20.27);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(100, 540, 20.63);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(101, 545, 21.02);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(102, 550, 21.41);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(103, 555, 21.81);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(104, 560, 22.19);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(105, 565, 22.59);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(106, 570, 23.0);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(107, 575, 23.41);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(108, 580, 23.82);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(109, 585, 24.22);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(110, 590, 24.64);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(111, 595, 25.05);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(112, 600, 25.49);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(113, 605, 25.91);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(114, 610, 26.34);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(115, 615, 26.77);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(116, 620, 27.21);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(117, 625, 27.65);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(118, 630, 28.11);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(119, 635, 28.55);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(120, 640, 29.0);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(121, 645, 29.19);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(122, 650, 29.91);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(123, 655, 30.37);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(124, 660, 30.84);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(125, 665, 31.3);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(126, 670, 31.77);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(127, 675, 32.25);
INSERT INTO vidrio_n ("id_vidrio_n", "centimetros", "precio") VALUES(128, 680, 32.73);

--vidirio sr
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(1, 45, 0.42);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(2, 50, 0.53);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(3, 55, 0.62);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(4, 60, 0.74);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(5, 65, 0.87);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(6, 70, 1.01);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(7, 75, 1.16);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(8, 80, 1.31);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(9, 85, 1.48);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(10, 90, 1.66);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(11, 95, 1.86);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(12, 100, 2.05);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(13, 105, 2.28);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(14, 110, 2.5);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(15, 115, 2.72);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(16, 120, 2.96);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(17, 125, 3.22);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(18, 130, 3.48);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(19, 135, 3.76);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(20, 140, 4.04);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(21, 145, 4.33);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(22, 150, 4.63);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(23, 155, 4.95);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(24, 160, 5.28);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(25, 165, 5.6);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(26, 170, 5.95);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(27, 175, 6.31);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(28, 180, 6.67);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(29, 185, 7.06);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(30, 190, 7.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(31, 195, 7.83);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(32, 200, 8.24);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(33, 205, 8.66);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(34, 210, 9.09);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(35, 215, 9.52);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(36, 220, 9.97);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(37, 225, 10.43);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(38, 230, 10.89);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(39, 235, 11.38);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(40, 240, 11.86);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(41, 245, 12.36);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(42, 250, 12.88);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(43, 255, 13.4);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(44, 260, 13.92);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(45, 265, 14.46);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(46, 270, 15.02);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(47, 275, 15.57);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(48, 280, 16.15);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(49, 285, 16.73);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(50, 290, 17.32);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(51, 295, 17.91);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(52, 300, 18.54);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(53, 305, 19.16);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(54, 310, 19.79);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(55, 315, 20.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(56, 320, 21.09);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(57, 325, 21.75);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(58, 330, 23.11);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(59, 335, 23.8);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(60, 340, 24.51);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(61, 345, 25.22);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(62, 350, 25.95);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(63, 355, 26.69);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(64, 360, 27.43);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(65, 365, 28.18);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(66, 370, 28.96);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(67, 375, 29.73);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(68, 380, 30.52);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(69, 385, 31.32);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(70, 390, 32.12);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(71, 395, 32.94);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(72, 400, 33.11);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(73, 405, 33.77);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(74, 410, 34.62);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(75, 415, 35.46);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(76, 420, 36.32);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(77, 425, 37.19);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(78, 430, 38.08);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(79, 435, 38.96);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(80, 440, 39.87);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(81, 445, 40.78);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(82, 450, 41.7);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(83, 455, 42.63);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(84, 460, 43.58);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(85, 465, 44.53);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(86, 470, 45.49);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(87, 475, 46.46);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(88, 480, 47.45);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(89, 485, 48.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(90, 490, 49.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(91, 495, 50.45);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(92, 500, 51.48);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(93, 505, 52.52);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(94, 510, 53.56);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(95, 515, 54.61);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(96, 520, 55.68);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(97, 525, 56.76);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(98, 530, 57.84);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(99, 535, 58.94);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(100, 540, 60.05);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(101, 545, 61.17);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(102, 550, 62.3);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(103, 555, 63.43);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(104, 560, 64.57);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(105, 565, 65.74);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(106, 570, 66.9);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(107, 575, 68.08);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(108, 580, 69.28);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(109, 585, 70.47);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(110, 590, 71.68);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(111, 595, 72.9);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(112, 600, 74.13);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(113, 605, 75.37);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(114, 610, 76.62);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(115, 615, 77.88);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(116, 620, 79.16);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(117, 625, 80.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(118, 630, 81.73);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(119, 635, 83.03);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(120, 640, 84.34);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(121, 645, 85.67);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(122, 650, 87.0);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(123, 655, 88.35);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(124, 660, 89.7);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(125, 665, 91.07);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(126, 670, 92.44);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(127, 675, 93.82);
INSERT INTO vidrio_sr ("id_vidrio_sr", "centimetros", "precio") VALUES(128, 680, 95.21);







